BEGIN;
DELETE FROM "django_admin_log";
DELETE FROM "convivencia_tiposamonestaciones";
DELETE FROM "convivencia_sanciones";
DELETE FROM "centro_alumnos";
DELETE FROM "auth_permission";
DELETE FROM "convivencia_amonestaciones";
DELETE FROM "centro_cursos_EquipoEducativo";
DELETE FROM "centro_departamentos";
DELETE FROM "auth_group";
DELETE FROM "django_session";
DELETE FROM "auth_user";
DELETE FROM "auth_group_permissions";
DELETE FROM "auth_user_user_permissions";
DELETE FROM "django_content_type";
DELETE FROM "centro_cursos";
DELETE FROM "centro_areas_Departamentos";
DELETE FROM "centro_profesores";
DELETE FROM "centro_areas";
DELETE FROM "auth_user_groups";
COMMIT;
